name = "finance-api"
compatibility_date = "2024-02-08"
main = "src/index.ts"

# Enable workers.dev subdomain
workers_dev = true

# Custom domain route
routes = [
  { pattern = "api.finance.szilagyibence.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "finance-db"
database_id = "552d89d1-dbde-442b-b9fa-542d028f9db8"

[triggers]
crons = ["0 0 1 * *"] # Run monthly on the 1st
